# Generated by Django 3.1.1 on 2020-09-11 12:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Agrege su nombre', max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'Debe introducir dos caracteres')])),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(default=0)),
                ('edad', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vuelo', models.CharField(help_text='Agregue tipo de vuelo', max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'Debe introducir dos caracteres')])),
                ('estado', models.CharField(help_text='Agregue estado de vuelo', max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'Debe introducir dos caracteres')])),
                ('clase', models.CharField(help_text='Agregue clase de vuelo', max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'Debe introducir dos caracteres')])),
                ('origen', models.CharField(help_text='Agregue origen', max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'Debe introducir dos caracteres')])),
                ('destino', models.CharField(help_text='Agregue destino', max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'Debe introducir dos caracteres')])),
                ('fecha_salida', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de salida')),
                ('fecha_regreso', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de regreso')),
                ('clientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.cliente')),
            ],
        ),
    ]
