# Generated by Django 3.1.1 on 2020-09-16 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20200915_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vuelo', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='tipo_vuelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.tipos'),
        ),
    ]
